name: Web Security Scanner

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'Target URL to scan (must be your own website)'
        required: true
        type: string
      username:
        description: 'Username for authentication (optional)'
        required: false
        type: string
      password:
        description: 'Password for authentication (optional)'
        required: false
        type: string
        default: ''
      scanner_type:
        description: 'Type of scanner to use'
        required: true
        type: choice
        options:
          - basic
          - advanced
      config_file:
        description: 'Configuration file path (for advanced scanner)'
        required: false
        type: string
        default: 'config.yaml'
  
  # Allow manual trigger with custom inputs
  repository_dispatch:
    types: [security-scan]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyyaml
        
    - name: Create config file
      run: |
        if [ ! -f "config.yaml" ]; then
          echo "Creating default config.yaml..."
          cat > config.yaml << 'EOF'
        scanner:
          max_threads: 3
          request_delay: 2.0
          timeout: 30
        payloads:
          xss:
            - '<script>alert("XSS")</script>'
            - '"><script>alert("XSS")</script>'
          sql_injection:
            - "' OR '1'='1"
            - "' OR 1=1--"
        EOF
        fi
        
    - name: Run Basic Security Scanner
      if: inputs.scanner_type == 'basic'
      run: |
        echo "Starting Basic Security Scanner..."
        echo "Target URL: ${{ inputs.target_url }}"
        echo "Username: ${{ inputs.username || 'None' }}"
        
        if [ -n "${{ inputs.username }}" ] && [ -n "${{ inputs.password }}" ]; then
          python web_security_scanner.py "${{ inputs.target_url }}" --username "${{ inputs.username }}" --password "${{ inputs.password }}"
        else
          python web_security_scanner.py "${{ inputs.target_url }}"
        fi
        
    - name: Run Advanced Security Scanner
      if: inputs.scanner_type == 'advanced'
      run: |
        echo "Starting Advanced Security Scanner..."
        echo "Target URL: ${{ inputs.target_url }}"
        echo "Username: ${{ inputs.username || 'None' }}"
        echo "Config file: ${{ inputs.config_file }}"
        
        if [ -n "${{ inputs.username }}" ] && [ -n "${{ inputs.password }}" ]; then
          python advanced_scanner.py "${{ inputs.target_url }}" --username "${{ inputs.username }}" --password "${{ inputs.password }}" --config "${{ inputs.config_file }}"
        else
          python advanced_scanner.py "${{ inputs.target_url }}" --config "${{ inputs.config_file }}"
        fi
        
    - name: Upload scan results
      uses: actions/upload-artifact@v3
      with:
        name: security-scan-results
        path: |
          *.json
          *.html
          *.csv
          *.log
        retention-days: 30
        
    - name: Create summary
      run: |
        echo "## Security Scan Summary" >> $GITHUB_STEP_SUMMARY
        echo "**Target URL:** ${{ inputs.target_url }}" >> $GITHUB_STEP_SUMMARY
        echo "**Scanner Type:** ${{ inputs.scanner_type }}" >> $GITHUB_STEP_SUMMARY
        echo "**Scan Date:** $(date)" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Generated Reports:" >> $GITHUB_STEP_SUMMARY
        
        # List generated files
        for file in *.json *.html *.csv *.log; do
          if [ -f "$file" ]; then
            echo "- \`$file\`" >> $GITHUB_STEP_SUMMARY
          fi
        done
        
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Note:** Download the artifacts above to view detailed scan results." >> $GITHUB_STEP_SUMMARY
