name: Simple Security Scanner

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'Target URL to scan (must be your own website)'
        required: true
        type: string
      username:
        description: 'Username for authentication (optional)'
        required: false
        type: string
      password:
        description: 'Password for authentication (optional)'
        required: false
        type: string

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Run Simple Security Scanner
      run: |
        echo "Starting Simple Security Scanner..."
        echo "Target URL: ${{ inputs.target_url }}"
        
        if [ -n "${{ inputs.username }}" ] && [ -n "${{ inputs.password }}" ]; then
          python working_scanner.py "${{ inputs.target_url }}" --username "${{ inputs.username }}" --password "${{ inputs.password }}" --non-interactive
        else
          python working_scanner.py "${{ inputs.target_url }}" --non-interactive
        fi
        
    - name: Upload scan results
      uses: actions/upload-artifact@v4
      with:
        name: security-scan-results
        path: |
          *.json
        retention-days: 30
        
    - name: Create summary
      run: |
        echo "## Simple Security Scan Summary" >> $GITHUB_STEP_SUMMARY
        echo "**Target URL:** ${{ inputs.target_url }}" >> $GITHUB_STEP_SUMMARY
        echo "**Scan Date:** $(date)" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [ -f "*.json" ]; then
          echo "### Generated Reports:" >> $GITHUB_STEP_SUMMARY
          for file in *.json; do
            if [ -f "$file" ]; then
              echo "- \`$file\`" >> $GITHUB_STEP_SUMMARY
            fi
          done
        else
          echo "No reports generated." >> $GITHUB_STEP_SUMMARY
        fi
        
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Note:** Download the artifacts above to view detailed scan results." >> $GITHUB_STEP_SUMMARY
